title: taiko-guide

description: An English-language guide to Taiko no Tatsujin

url: https://caaiitlin.github.io

baseurl: /taiko-guide

theme: just-the-docs

color_scheme: dark
logo: "/assets/logos/logo2.png"

favicon_ico: "/assets/favicon/favicon.png"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple