title: taiko.guide

description: An English-language guide and documentation project for Taiko no Tatsujin (太鼓の達人).

url: https://taiko.guide

baseurl: ""

theme: just-the-docs

color_scheme: dark
logo: "/assets/logos/logo.png"

favicon_ico: "/assets/favicon/favicon.png"

callouts:
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow
  diff:
    title: PC/Console Difference
    color: gray
