title: taiko.guide

description: An English-language guide and documentation project for Taiko no Tatsujin (太鼓の達人).

url: https://taiko.guide

baseurl: ""

theme: just-the-docs

color_scheme: dark
logo: "/assets/logos/logo.png"

favicon_ico: "/assets/favicon/favicon.png"

nav_external_links:
  - title: taiko.guide on GitHub
    url: https://github.com/caaiitlin/taiko.guide
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

callouts:
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow
  fact:
    title: Fun Fact
    color: yellow
